version: "3.0"
services:
  exos-flask:
    build:
      context: .
    container_name: exos-flask
    image: jupyter-image-custom2
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - 8888:8888
      - 6006:6006
      - 5000:5000
    volumes:
      - ../:/usr/src/exos-flask
    command: sh -c "
      cd ../../usr/src/exos-flask
      && jupyter notebook --ip='0.0.0.0' --port=8888 --no-browser --allow-root --NotebookApp.token='' --NotebookApp.password=''"
